<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>

        <ExcelDnaRuntimeVersion>v8.0</ExcelDnaRuntimeVersion>

        <RootNamespace>XLS_Memory_Lib</RootNamespace>
        <AssemblyName>XLS-Memory-Lib</AssemblyName>

        <UseWindowsForms>false</UseWindowsForms>

        <EnableDynamicLoading>true</EnableDynamicLoading>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

        <RunExcelDnaPack>true</RunExcelDnaPack>

        <ExcelAddInFileName>XLS-Memory-Lib</ExcelAddInFileName>
        <ExcelDnaCreate32BitAddIn>false</ExcelDnaCreate32BitAddIn>
        <ExcelDnaCreate64BitAddIn>true</ExcelDnaCreate64BitAddIn>

        <ExcelDna64BitAddInSuffix>%none%</ExcelDna64BitAddInSuffix>
        <ExcelDnaPackXllSuffix>%none%</ExcelDnaPackXllSuffix>

        <ExcelDnaPackCompressResources>true</ExcelDnaPackCompressResources>
        <ExcelDnaPackRunMultithreaded>true</ExcelDnaPackRunMultithreaded>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ExcelDna.AddIn" Version="1.10.0-preview4" />
    </ItemGroup>

    <ItemGroup>
        <None Include="XLS-Memory-Lib.dna">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Memory-Db\Memory-Db.csproj"/>
        <ProjectReference Include="..\SqliteDB-Memory-Lib\SqliteDB-Memory-Lib.csproj"/>
        <ProjectReference Include="..\LiteDB-Memory-Lib\LiteDB-Memory-Lib.csproj"/>
        <ProjectReference Include="..\DuckDB-Memory-Lib\DuckDB-Memory-Lib.csproj"/>
    </ItemGroup>

    <PropertyGroup>
        <NativePlatform Condition="'$(PlatformTarget)' == ''">x64</NativePlatform>
        <NativePlatform Condition="'$(PlatformTarget)' != ''">$(PlatformTarget)</NativePlatform>
        <NativeRid Condition="'$(NativePlatform)' == 'x64'">win-x64</NativeRid>
        <NativeRid Condition="'$(NativePlatform)' == 'x86'">win-x86</NativeRid>
    </PropertyGroup>

    <Target Name="CopyNativeLibraries" AfterTargets="ExcelDnaPack">
        <PropertyGroup>
            <MyPublishDir>$(TargetDir)publish\</MyPublishDir>
            <NativePublishDir>$(MyPublishDir)native\$(NativePlatform)\</NativePublishDir>
        </PropertyGroup>

        <MakeDir Directories="$(NativePublishDir)" />

        <ItemGroup>
            <NativeDlls Include="$(TargetDir)runtimes\$(NativeRid)\Native\*.dll" />
        </ItemGroup>

        <Copy
                SourceFiles="@(NativeDlls)"
                DestinationFolder="$(NativePublishDir)"
                SkipUnchangedFiles="false"
                Condition="'@(NativeDlls)' != ''" />
    </Target>
    
</Project>