<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>DuckDb_Memory_Lib</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Update="DuckDB.NET.Data.Full" Version="1.4.4" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\Shared\ConnectionManagerBase.cs" Link="Shared\ConnectionManagerBase.cs" />
    </ItemGroup>

</Project>
