<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Memory.DB</PackageId>
        <Version>1.0.0</Version>
        <Authors>Dagalon</Authors>
        <Description>
            A collection of helper libraries that make it simple to spin up disposable,
            in-memory database engines for local development, automated tests, and prototypes.
        </Description>

        <RepositoryUrl>https://github.com/Dagalon/MemoryDb-Lib</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteDb-Memory-Lib\LiteDb-Memory-Lib.csproj" />
        <ProjectReference Include="..\SqliteDB-Memory-Lib\SqliteDB-Memory-Lib.csproj" />
        <ProjectReference Include="..\DuckDB-Memory-Lib\DuckDB-Memory-Lib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.Data.Sqlite" Version="11.0.0-preview.5.26302.115" />
    </ItemGroup>

</Project>
